# Generated by Django 5.2.1 on 2025-06-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0004_courseprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
